In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv(
    "https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true",
    storage_options={"User-Agent": "Our World In Data data fetch/1.0"}
)

# Fetch the metadata
metadata = requests.get(
    "https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true"
).json()

In [2]:
df.iloc[30:35]

         entity code  year  life_expectancy_0
30  Afghanistan  AFG  1980            39.2581
31  Afghanistan  AFG  1981            39.4058
32  Afghanistan  AFG  1982            36.0577
33  Afghanistan  AFG  1983            36.5174
34  Afghanistan  AFG  1984            31.4732

In [3]:
df_1970 = df[df["year"] == 1970]
df_1970[df_1970["entity"].str.startswith("K")]

          entity      code  year  life_expectancy_0
9591  Kazakhstan       KAZ  1970            60.0490
9668       Kenya       KEN  1970            54.1427
9742    Kiribati       KIR  1970            54.3802
9816      Kosovo  OWID_KOS  1970            54.0023
9891      Kuwait       KWT  1970            67.9771
9965  Kyrgyzstan       KGZ  1970            58.1840

In [4]:
df[df["entity"].str.contains("Mex", regex=True)]

       entity code  year  life_expectancy_0
12372  Mexico  MEX  1893            23.2900
12373  Mexico  MEX  1894            26.6200
12374  Mexico  MEX  1895            29.5200
12375  Mexico  MEX  1896            28.8000
12376  Mexico  MEX  1897            26.2400
...       ...  ...   ...                ...
12488  Mexico  MEX  2019            74.5302
12489  Mexico  MEX  2020            70.4492
12490  Mexico  MEX  2021            69.7499
12491  Mexico  MEX  2022            73.9731
12492  Mexico  MEX  2023            75.0690

[121 rows x 4 columns]

In [5]:
df.set_index(["code", "year"])

                entity  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138
     1953  Afghanistan            29.4521
     1954  Afghanistan            29.6975
...                ...                ...
ZWE  2019     Zimbabwe            61.0603
     2020     Zimbabwe            61.5300
     2021     Zimbabwe            60.1347
     2022     Zimbabwe            62.3601
     2023     Zimbabwe            62.7748

[21565 rows x 2 columns]

In [6]:
df.loc[df["code"].isnull()]

                                      entity code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [7]:
df.describe()

               year  life_expectancy_0
count  21565.000000       21565.000000
mean    1976.992812          61.942232
std       38.461606          12.925912
min     1543.000000          10.989100
25%     1962.000000          52.703000
50%     1982.000000          64.479900
75%     2003.000000          71.978900
max     2023.000000          86.372400

In [8]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

entity               0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [9]:
df.shape

(20217, 4)

In [10]:
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [11]:
df_1970_2023 = df[(df["year"] >= 1970)]
resultado = (
    df_1970_2023.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
Nigeria                     47.721319
Mali                        48.654591
Somalia                     48.799163
Angola                      49.022959
East Timor                  49.192574
Name: life_expectancy_0, dtype: float64

In [12]:
df_1909_1930 = df[(df["year"] >= 1909) & (df["year"] <= 1930)]
df_1909_1930[df_1909_1930["entity"].str.contains("Mex", regex=True)]

       entity code  year  life_expectancy_0
12388  Mexico  MEX  1909              29.21
12389  Mexico  MEX  1910              28.00
12390  Mexico  MEX  1920              34.00
12391  Mexico  MEX  1922              32.60
12392  Mexico  MEX  1923              33.50
12393  Mexico  MEX  1924              32.80
12394  Mexico  MEX  1925              32.10
12395  Mexico  MEX  1926              34.20
12396  Mexico  MEX  1927              40.30
12397  Mexico  MEX  1928              34.50
12398  Mexico  MEX  1929              35.40
12399  Mexico  MEX  1930              34.00